name: nucleotide_transformer_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip
  - cudatoolkit=11.8
  - cudnn
  - numpy=1.26.4
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - matplotlib
  - seaborn
  - jupyter
  - tqdm=4.67.1
  - pip:
    - torch==2.6.0+cu118
    - torchvision==0.21.0+cu118
    - torchaudio==2.6.0+cu118
    - transformers==4.57.1
    - datasets==4.2.0
    - huggingface-hub==0.35.3
    - tokenizers==0.22.1
    - nucleotide-transformer==0.0.1
    - safetensors==0.6.2
    - accelerate
    - requests==2.32.5
    - urllib3==2.5.0
    - pillow==11.3.0
    - openpyxl==3.1.5